Story05/Production/gettingstarted/urls.py
from django.urls import path, include

from django.contrib import admin
import lessons.views

admin.autodiscover()

# To add a new path, first import the app:
# import blog
#
# Then add the new path:
# path('blog/', blog.urls, name="blog")
#
# Learn more here: https://docs.djangoproject.com/en/2.1/topics/http/urls/

urlpatterns = [
    path("", lessons.views.index, name="index"),

    path("schedule/", include('lessons.urls'), name="schedule"),

    path("db/", lessons.views.db, name="db"),
    path("admin/", admin.site.urls),
]

Story05/Production/lessons/urls.py
from django.urls import path

from django.contrib import admin
import lessons.views

admin.autodiscover()

# To add a new path, first import the app:
# import blog
#
# Then add the new path:
# path('blog/', blog.urls, name="blog")
#
# Learn more here: https://docs.djangoproject.com/en/2.1/topics/http/urls/

app_name = 'lessons'
urlpatterns = [
    path("", lessons.views.index, name="index"),
    path("delete_lesson", lessons.views.lesson_wipe, name="clear_lesson"),
    path("add_lesson", lessons.views.add_lesson, name="add_lesson"),
    path("view_lesson", lessons.views.lesson_view, name="view_lesson"),
    path("add", lessons.views.add, name="add"),
    path("delete", lessons.views.delete, name="delete"),
]

Story05/Production/lessons/models.py
from random import randint

from django.db import models
from django.http import request
from django.shortcuts import get_object_or_404, redirect


class Lesson(models.Model):
    name = models.CharField(max_length=500)
    lecturer = models.CharField(max_length=40)
    sks = models.IntegerField(default=0)
    description = models.TextField()
    semester = models.CharField(max_length=9)
    room = models.CharField(max_length=20)

    def delete(self):
        self.delete()

    def __str__(self):
        return self.name

Story05/Production/lessons/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404

from .models import Lesson


# Create your views here.
def index(request):
    # return HttpResponse('Hello from Python!')
    if not request:
        return render("down.html")

    return render(request, "lessons_home.html")


def add_lesson(request):
    try:
        all_lessons = Lesson.objects.all()
        all_lessons.get(0).DoesNotExist
    except Exception as e:
        return render(request, "lessons_add_new.html")

    lesson_count = Lesson.objects.all().count()
    context = {'all_lessons': all_lessons, 'lesson_count': lesson_count}
    return render(request, "lessons_add.html", context)


def lesson_view(request):
    if Lesson.objects.exists():
        context = {'all_lessons': 0}
    else:
        all_lessons = Lesson.objects.all()
        context = {'all_lessons': all_lessons}

    return render(request, "lessons_view.html", context)


def lesson_wipe(request):
    try:
        all_lessons = Lesson.objects.all()
    except not all_lessons.exists():
        raise Http404("Question does not exist")

    lesson_count = Lesson.objects.all().count()
    context = {'all_lessons': all_lessons, 'lesson_count': lesson_count}
    return render(request, "lessons_delete.html", context)


def db(request):
    all_lessons = Lesson.objects.all()
    all_lessons.save()
    return render(request, "db.html", {"lessons": all_lessons})


def add(request):
    the_values = {
        "key": "the_values"
    }
    for key, value in request.POST.items():
        the_values[key] = value

    new_lesson = Lesson(name=the_values["lesson"], lecturer=the_values["lecturer"],
                        description=the_values["description"], sks=the_values["credits"], room=the_values["room"],
                        semester=the_values["semester"])

    new_lesson.save()
    return redirect('lessons:view_lesson')


def delete(request):
    name = request.POST.get("name")
    lessons = Lesson.objects.all()
    lesson = lessons.filter(name=name)
    lesson.delete()
    return redirect('lessons:view_lesson')

Story05/Production/gettingstarted/templates/down.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors"><!-- -->
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Top navbar example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/cover/">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/checkout/">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/grid/">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/navbar-static/">

    <!-- Bootstrap core CSS -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="navbar-top.css" rel="stylesheet">
</head>
<body>
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <main role="main" class="inner cover">
            <h1 class="cover-heading">Sorry, Website is down</h1>
        </main>
    </div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

Story05/Production/gettingstarted/templates/lessons.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors"><!-- -->
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Top navbar example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/cover/">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/checkout/">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/grid/">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/navbar-static/">

    <!-- Bootstrap core CSS -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="navbar-top.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="#">Top navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'add' %}">Add</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'view' %}">View</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'wipe' %}">Delete</a>
            </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

{% block content %}{% endblock %}

        <footer class="my-5 pt-5 text-muted text-center text-small">
            <p class="mb-1">Made by Linus with Bootstrap</p>
        </footer>
</body>
</html>

Story05/Production/gettingstarted/templates/lessons_add.html
{% extends "lessons.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="py-5 text-center">
            <h2>Checkout form</h2>
            <p class="lead">Below is an example form built entirely with Bootstrap’s form controls. Each required form
                group has a validation state that can be triggered by attempting to submit the form without completing
                it.</p>
        </div>

        <div class="row">
            <div class="col-md-4 order-md-2 mb-4">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Your lessons</span>
                    <span class="badge badge-secondary badge-pill">{{ lesson_count }}</span>
                </h4>

                <ul class="list-group mb-3">
                    {% for lesson in all_lessons %}
                        <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div>
                                <h6 class="my-0">{{ lesson.name }}</h6>
                                <small class="text-muted">{{ lesson.semester }}</small>
                            </div>
                            <span class="text-muted">{{ lesson.sks }}</span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-8 order-md-1">
                <h4 class="mb-3">Add lesson</h4>
                <form class="needs-validation" novalidate>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="firstName">Lesson name</label>
                            <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
                            <div class="invalid-feedback">
                                Valid lesson name is required.
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="lastName">Lecturer</label>
                            <input type="text" class="form-control" id="lastName" placeholder="" value="" required>
                            <div class="invalid-feedback">
                                Valid Lecturer is required.
                            </div>
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="email">Description <span class="text-muted">(Optional)</span></label>
                        <input type="email" class="form-control" id="email" placeholder="">
                        <div class="invalid-feedback">
                            Please enter a lesson description.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="address">Credits</label>
                        <input type="text" class="form-control" id="address" placeholder="12" required>
                        <div class="invalid-feedback">
                            Please enter a number of credits.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="address2">Lesson room <span class="text-muted">(Optional)</span></label>
                        <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
                    </div>

                    <div class="row">
                        <div class="col-md-4 mb-3">
                            <label for="state">Semester</label>
                            <select class="custom-select d-block w-100" id="state" required>
                                <option value="">Choose...</option>
                                <option>2018/2019</option>
                                <option>2019/2020</option>
                                <option>2020/2021</option>
                                <option>2021/2022</option>
                                <option>2022/2023</option>
                                <option>2023/2024</option>
                            </select>
                            <div class="invalid-feedback">
                                Please provide a valid semester.
                            </div>
                        </div>
                    </div>

                    <hr class="mb-4">
                    <button class="btn btn-primary btn-lg btn-block" type="submit">Add lesson</button>
                </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
    <script src="form-validation.js"></script></body>
{% endblock %}

Story05/Production/gettingstarted/templates/lessons_home.html
{% extends "lessons.html" %}
{% load static %}

{% block content %}
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <main role="main" class="inner cover">
            <h1 class="cover-heading">Lessons, Register them</h1>
            <p class="lead">
                <a href="{% url 'add' %}" class="btn btn-lg btn-secondary">Add</a>
                <a href="{% url 'view' %}" class="btn btn-lg btn-secondary">View</a>
            </p>
        </main>
    </div>
{% endblock %}

Story05/Production/lessons/templates/lessons.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lesson Registrar</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Linus using Bootstrap Template">
    <meta name="generator" content="Jekyll v4.1.1">
    <script src="../static/bootstrap/js/bootstrap.bundle.min.js"></script>
    <title>Top navbar example · Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" href="../static/favicon.ico">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="../static/css/navbar-top.css" rel="stylesheet">
</head>
<body style="min-height: 100%;">
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="{% url 'index' %}">Lessons</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'lessons:add_lesson' %}">Add</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'lessons:view_lesson' %}">View</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'lessons:clear_lesson' %}">Delete</a>
            </li>
        </ul>
    </div>
</nav>

{% block content %}{% endblock %}

</body>
</html>

Story05/Production/lessons/templates/lessons_add.html
{% extends "lessons.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="py-5 text-center">
            <h2>Add Lesson</h2>
            <p class="lead">Got a lesson you want to register? Add it below!</p>
        </div>

        <div class="row">
            <div class="col-md-4 order-md-2 mb-4">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Your lessons</span>
                    <span class="badge badge-secondary badge-pill">{{ lesson_count }}</span>
                </h4>

                <ul class="list-group mb-3">
                    {% for lesson in all_lessons %}
                        <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div>
                                <h6 class="my-0">{{ lesson.name }}</h6>
                                <small class="text-muted">{{ lesson.semester }}</small>
                            </div>
                            <span class="text-muted">{{ lesson.sks }}</span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-8 order-md-1">
                <h4 class="mb-3">Add lesson</h4>
                <form class="needs-validation" action="{% url 'lessons:add' %}" method="post" novalidate>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="lesson">Lesson name</label>
                            <input type="text" class="form-control" id="lesson" name="lesson" placeholder="" value="{{ lesson.name }}" required>
                            <div class="invalid-feedback">
                                Valid lesson name is required.
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="lecturer">Lecturer</label>
                            <input type="text" class="form-control" id="lecturer" name="lecturer" placeholder="" value="{{ lesson.lecturer }}" required>
                            <div class="invalid-feedback">
                                Valid Lecturer is required.
                            </div>
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="description">Description</label>
                        <input type="text" class="form-control" id="description" name="description" placeholder="" value="{{ lesson.description }}">
                        <div class="invalid-feedback">
                            Please enter a lesson description.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="credits">Credits</label>
                        <input type="text" class="form-control" id="credits" name="credits" placeholder="12" value="{{ lesson.sks }}" required>
                        <div class="invalid-feedback">
                            Please enter a number of credits.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="room">Lesson room <span class="text-muted">(Optional)</span></label>
                        <input type="text" class="form-control" id="room" name="room" placeholder="Lab 103" value="{{ lesson.sks }}">
                    </div>

                    <div class="row">
                        <div class="col-md-4 mb-3">
                            <label for="semester">Semester</label>
                            <select class="custom-select d-block w-100" id="semester" name="semester" required value="{{ lesson.semester }}">
                                <option value="">Choose...</option>
                                <option value="2018/2019">2018/2019</option>
                                <option value="2019/2020">2019/2020</option>
                                <option value="2020/2021">2020/2021</option>
                                <option value="2021/2022">2021/2022</option>
                                <option value="2022/2023">2022/2023</option>
                                <option value="2023/2024">2023/2024</option>
                            </select>
                            <div class="invalid-feedback">
                                Please provide a valid semester.
                            </div>
                        </div>
                    </div>

                    <hr class="mb-4">
                    <button class="btn btn-primary btn-lg btn-block" type="submit" value="add">Add lesson</button>
                </form>
            </div>
        </div>
    </div>
    <script src="../static/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="../static/js/form-validation.js"></script></body>
{% endblock %}

Story05/Production/lessons/templates/lessons_add_new.html
{% extends "lessons.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="py-5 text-center">
            <h2>Add Lesson</h2>
            <p class="lead">Got a lesson you want to register? Add it below!</p>
        </div>

        <div class="row">
            <div class="col-md-12 order-md-1">
                <h4 class="mb-4">Add lesson</h4>
                <form class="needs-validation" action="{% url 'lessons:add' %}" method="post" novalidate>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="lesson">Lesson name</label>
                            <input type="text" class="form-control" id="lesson" name="lesson" placeholder="" value="{{ lesson.name }}" required>
                            <div class="invalid-feedback">
                                Valid lesson name is required.
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="lecturer">Lecturer</label>
                            <input type="text" class="form-control" id="lecturer" name="lecturer" placeholder="" value="{{ lesson.lecturer }}" required>
                            <div class="invalid-feedback">
                                Valid Lecturer is required.
                            </div>
                        </div>
                    </div>

                    <div class="mb-4">
                        <label for="description">Description</label>
                        <input type="text" class="form-control" id="description" name="description" placeholder="" value="{{ lesson.description }}">
                        <div class="invalid-feedback">
                            Please enter a lesson description.
                        </div>
                    </div>

                    <div class="mb-4">
                        <label for="credits">Credits</label>
                        <input type="text" class="form-control" id="credits" name="credits" placeholder="12" value="{{ lesson.sks }}" required>
                        <div class="invalid-feedback">
                            Please enter a number of credits.
                        </div>
                    </div>

                    <div class="mb-4">
                        <label for="room">Lesson room <span class="text-muted">(Optional)</span></label>
                        <input type="text" class="form-control" id="room" name="room" placeholder="Lab 103" value="{{ lesson.sks }}">
                    </div>

                    <div class="row">
                        <div class="col-md-4 mb-3">
                            <label for="semester">Semester</label>
                            <select class="custom-select d-block w-100" id="semester" name="semester" required value="{{ lesson.semester }}">
                                <option value="">Choose...</option>
                                <option value="2018/2019">2018/2019</option>
                                <option value="2019/2020">2019/2020</option>
                                <option value="2020/2021">2020/2021</option>
                                <option value="2021/2022">2021/2022</option>
                                <option value="2022/2023">2022/2023</option>
                                <option value="2023/2024">2023/2024</option>
                            </select>
                            <div class="invalid-feedback">
                                Please provide a valid semester.
                            </div>
                        </div>
                    </div>

                    <hr class="mb-4">
                    <button class="btn btn-primary btn-lg btn-block" type="submit" value="add">Add lesson</button>
                </form>
            </div>
        </div>
    </div>
    <script src="../static/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="../static/js/form-validation.js"></script></body>
{% endblock %}

Story05/Production/lessons/templates/lessons_delete.html
{% extends "lessons.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="py-5 text-center">
            <h2>Delete lesson</h2>
            <p class="lead">Don't like that lesson? Yeet it with delete it!</p>
        </div>

        <div class="row">
            <div class="col-md-4 order-md-2 mb-4">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Your lessons</span>
                    <span class="badge badge-secondary badge-pill">{{ lesson_count }}</span>
                </h4>

                <ul class="list-group mb-3">
                    {% for lesson in all_lessons %}
                        <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div>
                                <h6 class="my-0">{{ lesson.name }}</h6>
                                <small class="text-muted">{{ lesson.semester }}</small>
                            </div>
                            <span class="text-muted">{{ lesson.sks }}</span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-8 order-md-1">
                <h4 class="mb-3">Add lesson</h4>
                <form class="needs-validation" action="{% url 'lessons:delete' %}" method="post" novalidate>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="firstName">Lesson name</label>
                            <input type="text" class="form-control" id="name" name="name" value="" placeholder="SDA" required>
                            <div class="invalid-feedback">
                                Valid lesson name is required.
                            </div>
                        </div>
                    </div>
                    <hr class="mb-4">
                    <button class="btn btn-primary btn-lg btn-block" type="submit">Delete</button>
                </form>
            </div>
        </div>
    </div>
    <script src="../static/js/form-validation.js"></script></body>
{% endblock %}

Story05/Production/lessons/templates/lessons_home.html
{% extends "lessons.html" %}
{% load static %}

{% block content %}
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <main role="main" class="inner cover">
            <h1 class="cover-heading">Lessons, Register them</h1>
            <p class="lead">
                <a href="{% url 'lessons:add_lesson' %}" class="btn btn-lg btn-secondary">Add</a>
                <a href="{% url 'lessons:view_lesson' %}" class="btn btn-lg btn-secondary">View</a>
            </p>
        </main>
    </div>
{% endblock %}

Story05/Production/lessons/templates/lessons_view.html
{% extends "lessons.html" %}
{% load static %}

{% block content %}

    <h1>List of Lessons</h1>
    <div class="row mb-3">
        <div class="col-md-2 themed-grid-col">Lesson</div>
        <div class="col-md-2 themed-grid-col">Lecturer</div>
        <div class="col-md-1 themed-grid-col">SKS</div>
        <div class="col-md-2 themed-grid-col">Room</div>
        <div class="col-md-2 themed-grid-col">Semester</div>
        <div class="col-md-3 themed-grid-col">Description</div>
    </div>
    <div class="row mb-1 bg-dark">
        <div class="col-md-12">.</div>
    </div>

    {% for lesson in all_lessons %}
        {% if not lesson.DoesNotExist %}
            <div class="row mb-3">
                <div class="col-md-2 themed-grid-col">{{ lesson.name }}</div>
                <div class="col-md-2 themed-grid-col">{{ lesson.lecturer }}</div>
                <div class="col-md-1 themed-grid-col">{{ lesson.sks }}</div>
                <div class="col-md-2 themed-grid-col">{{ lesson.room }}</div>
                <div class="col-md-2 themed-grid-col">{{ lesson.semester }}</div>
                <div class="col-md-2 themed-grid-col">{{ lesson.description }}</div>
                <form class="needs-validation" action="{% url 'lessons:delete' %}" method="post" novalidate>
                    {% csrf_token %}
                    <div class="col-md-1 themed-grid-col">
                        <button type="submit" class="btn btn-secondary" name="name" value="{{ lesson.name }}">Delete
                        </button>
                    </div>
                </form>
            </div>
        {% endif %}
        {% if lesson.DoesNotExist %}
            <div class="row mb-12">
                <div class="col-md-2 themed-grid-col">No Lessons Registered</div>
            </div>
        {% endif %}
    {% endfor %}
{% endblock %}